docker_image:                                           # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.2   # [ppc64le and os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.2   # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

c_compiler_version:        # [linux]
  - 9                      # [ppc64le]
  - 9                      # [aarch64]

cxx_compiler_version:      # [linux]
  - 9                      # [ppc64le]
  - 9                      # [aarch64]

fortran_compiler_version:  # [linux]
  - 9                      # [ppc64le]
  - 9                      # [aarch64]

cuda_compiler:
  - nvcc

cuda_compiler_version:
  - 11.2                   # [ppc64le]
  - 11.2                   # [aarch64]

cudnn:
  - undefined              # [ppc64le]
  - undefined              # [aarch64]

cdt_name:  # [linux]
  - cos7   # [ppc64le]
  - cos7   # [aarch64]
