c_compiler_version:
  - 10
cxx_compiler_version:
  - 10
cuda_compiler_version:
  - 11.6
fortran_compiler_version:
  - 10
cudnn:
  - 8
cdt_name:
  - cos7
docker_image:
  - quay.io/condaforge/linux-anvil-cuda:11.6           # [linux64]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.6   # [linux and ppc64le]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.6   # [linux and aarch64]

