{% set name = "ptxcompiler" %}
{% set version = "0.3.0" %}
{% set cuda_version = '.'.join(environ.get('CUDA', '11.6').split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/ptxcompiler/archive/refs/tags/{{ version }}.tar.gz
  sha256: 16c317010714d1e1960c433075f10e45eb0722b549fb0a71727e1a846d9798f9
  patches:
    - setup.py.patch

build:
  number: 2
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version != "11.6"]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
  host:
    - python
    - pip
    - cudatoolkit {{ cuda_version }}.*
  run:
    - python
    - numba >=0.54
    - cudatoolkit >={{ cuda_major ~ ".0" }},<={{ cuda_version }}
  run_constrained:
    - __cuda >={{ cuda_major ~ ".0" }},<={{ cuda_version }}

test:
  imports:
    - ptxcompiler

about:
  home: https://github.com/rapidsai/ptxcompiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PTX Static compiler and Numba patch

extra:
  recipe-maintainers:
  - prashantkhoje
