{% set name = "ptxcompiler" %}
{% set version = "0.5.0" %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.7").split(".")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/ptxcompiler/archive/refs/tags/{{ version }}.tar.gz
  sha256: d1b8783a832a36ca5ae5c3623e6730a69a44a72c249e21537ffcfce4511c9c1a

build:
  number: 0
  skip: true  # [(not linux) or cuda_compiler_version in (undefined, "None")]
  ignore_run_exports_from:
    - {{ compiler("cuda") }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
  host:
    - python
    - pip
    - cudatoolkit {{ cuda_compiler_version }}
  run:
    - python
    - numba >=0.54
    - cudatoolkit >={{ cuda_major ~ ".0" }},<={{ cuda_compiler_version }}
  run_constrained:
    - __cuda >={{ cuda_major ~ ".0" }}

test:
  imports:
    - ptxcompiler

about:
  home: https://github.com/rapidsai/ptxcompiler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PTX Static compiler and Numba patch

extra:
  recipe-maintainers:
    - prashantkhoje
    - bdice
    - jakirkham
